### PR TITLE
changes the flow to avoid dir and branch name collision

### PR DESCRIPTION
**Pull request by marcocarvalho**
**Description**: Fix flow to avoid problems when directory/files names on project root collides with  branch names. (https://caremessage.slack.com/archives/C0C9VQKV0/p1579027020001100)

**JIRA**: NO-JIRA

**How to Verify**: The test must be green

**SIMPLE PR TASKS**
- [ ] Pick at least one reviewer
- [x] Merge to *Staging*: See [test, It trys to merge to staging and see if the action works](https://github.com/CareMessagePlatform/check-if-merged/blob/master/.github/workflows/check_if_merged.yml)
- [x] Add necessary tags(QA, CI, Code Review, Code analysis, Code Coverage)
- [ ] Move JIRA story into Ready-for-QA

### CODE REVIEW

**Comment by marcocarvalho** [comment]
I tested on one of the repos that we are having problems and it worked.

image

**Comment by danielnc** [comment]
@marcocarvalho can we add a test to cover this scenario.

that is why I suggested that we had automated tests by circleci when we first built the repo, so we could add tests to avoid regressions 😉

**Comment by marcocarvalho** [comment]
@danielnc Can we add this in another PR? To unblock the projects with erros?

**Comment by danielnc** [comment]
@marcocarvalho we can't add code and merge that is not tested and fully covered . I decided to allow this when we had the first version of this check but that should have not been an option since it goes against our policies and best practices

**Comment by marcocarvalho** [comment]
Just listing some resources to my future reference (I'll work more on this tomorrow):

https://circleci.com/docs/2.0/using-shell-scripts/

https://github.com/shellspec/shellspec
https://github.com/kward/shunit2
https://github.com/sstephenson/bats

**Comment by danielnc** [comment]
@marcocarvalho any updates? I am tagged as reviewer, if not I'll close this PR

**Pull request closed without merging**
